config/routes.rb
NewProject::Application.routes.draw do
  resources :machines

  resources :users

  get "users/new"

  get "pages/home"

  get "pages/contact"

  get "pages/about"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'

  root :to => 'pages#home'

end

app/models/machine.rb
class Machine < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :machines
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  # GET /machines
  # GET /machines.xml
  def index
    @machines = Machine.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @machines }
    end
  end

  # GET /machines/1
  # GET /machines/1.xml
  def show
    @machine = Machine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @machine }
    end
  end

  # GET /machines/new
  # GET /machines/new.xml
  def new
    @machine = Machine.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @machine }
    end
  end

  # GET /machines/1/edit
  def edit
    @machine = Machine.find(params[:id])
  end

  # POST /machines
  # POST /machines.xml
  def create
    @machine = Machine.new(params[:machine])

    respond_to do |format|
      if @machine.save
        format.html { redirect_to(@machine, :notice => 'Machine was successfully created.') }
        format.xml  { render :xml => @machine, :status => :created, :location => @machine }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @machine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /machines/1
  # PUT /machines/1.xml
  def update
    @machine = Machine.find(params[:id])

    respond_to do |format|
      if @machine.update_attributes(params[:machine])
        format.html { redirect_to(@machine, :notice => 'Machine was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @machine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /machines/1
  # DELETE /machines/1.xml
  def destroy
    @machine = Machine.find(params[:id])
    @machine.destroy

    respond_to do |format|
      format.html { redirect_to(machines_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  @title = "Home"
  end

  def contact
  @title = "Contact"
  end

  def about
  @title = "About"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tag %>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->    
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  </head>
  <body>
    <div class="container">
      <header>
        <nav class="round">
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
          </ul>
        </nav>
      </header>
      <section class="round">
        <%= yield %>
      </section>
        <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/machines/_form.html.erb
<%= form_for(@machine) do |f| %>
  <% if @machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@machine.errors.count, "error") %> prohibited this machine from being saved:</h2>

      <ul>
      <% @machine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :machine %><br />
    <%= f.text_field :machine %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/machines/edit.html.erb
<h1>Editing machine</h1>

<%= render 'form' %>

<%= link_to 'Show', @machine %> |
<%= link_to 'Back', machines_path %>

app/views/machines/index.html.erb
<h1>Listing machines</h1>

<table>
  <tr>
    <th>Machine</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @machines.each do |machine| %>
  <tr>
    <td><%= machine.machine %></td>
    <td><%= machine.name %></td>
    <td><%= link_to 'Show', machine %></td>
    <td><%= link_to 'Edit', edit_machine_path(machine) %></td>
    <td><%= link_to 'Destroy', machine, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Want to reserve another machine', new_machine_path %>
&#160;&#160;&#160; <%= link_to 'Nah, Take me Home !', root_path %>

app/views/machines/new.html.erb
<h1>New machine</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

&#160;&#160;&#160; <%= link_to 'Take me Home !', root_path %>

&#160;&#160;&#160; <%= link_to 'Show me list of reservations', machines_path %>

app/views/machines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Machine:</b>
  <%= @machine.machine %>
</p>

<p>
  <b>Name:</b>
  <%= @machine.name %>
</p>


<%= link_to 'Edit', edit_machine_path(@machine) %> |
<%= link_to 'Back', machines_path %>
&#160;&#160;&#160; <%= link_to 'Take me Home !', root_path %>

app/views/pages/about.html.erb
    <h1>About</h1>
    <p>
      Machine Reservation System
    </p>

app/views/pages/contact.html.erb
    <h1>Contact</h1>
    <p>
      Contact Information : Naveen Chekuri
                            Email: nchekuri@andrew.cmu.edu
    </p>

app/views/pages/help.html.erb
    <h1>Help</h1>
    <p>
        Get help on Ruby on Rails Tutorial at the
        <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
    </p>

app/views/pages/home.html.erb
    <p>
      <br />
      <br />
      <center> Welcome to Machine Reservation System </center>
    </p>

<%= link_to "Book a Machine", signup_path, :class => "signup_button round" %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>
&#160;&#160;&#160; <%= link_to 'Take me to machine reservation', new_machine_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

&#160;&#160;&#160; <%= link_to 'Take me directly to machine reservation', new_machine_path %>
&#160;&#160;&#160; <%= link_to 'Show me the list of users', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>